# Generated by Django 5.0.3 on 2024-07-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_address_email_remove_address_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='telephone',
        ),
    ]
