# Generated by Django 5.0.3 on 2024-07-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_address_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'نشانی', 'verbose_name_plural': 'نشانی ها'},
        ),
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
