# Generated by Django 5.0.3 on 2024-09-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.PositiveIntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
