# Generated by Django 5.0.3 on 2024-09-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_address_phone_alter_address_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.BigIntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
