# Generated by Django 5.0.3 on 2025-02-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_address_phone_alter_address_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='expiration_date',
            new_name='created_at',
        ),
    ]
