# Generated by Django 5.0.3 on 2024-04-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_body',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
