# Generated by Django 5.0.3 on 2024-07-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_short_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='pr', to='product.product'),
        ),
    ]
