# Generated by Django 5.0.3 on 2024-07-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_category_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SIM',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سایز سیمکارت'),
        ),
        migrations.AddField(
            model_name='product',
            name='SIM_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تعداد سیمکارت'),
        ),
        migrations.AddField(
            model_name='product',
            name='body_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متریال بدنه'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ابعاد'),
        ),
        migrations.AddField(
            model_name='product',
            name='introduction_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='زمان معرفی'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وزن'),
        ),
    ]
