# Generated by Django 5.0.3 on 2024-07-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_sim_product_sim_num_product_body_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=1, upload_to='product/images'),
            preserve_default=False,
        ),
    ]
