# Generated by Django 5.0.3 on 2024-07-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percent_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
