# Generated by Django 5.0.3 on 2024-07-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_percent_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
