# Generated by Django 5.0.3 on 2024-07-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
