# Generated by Django 5.0.3 on 2024-07-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
