# Generated by Django 5.0.3 on 2024-07-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_time',
        ),
    ]
