# Generated by Django 5.0.3 on 2024-08-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_specialssle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialSsle',
            new_name='SpecialSale',
        ),
    ]
