# Generated by Django 5.0.3 on 2024-08-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_rename_specialssle_specialsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialsale',
            name='sale_price',
            field=models.IntegerField(),
        ),
    ]
