# Generated by Django 5.0.3 on 2024-08-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_specialsale_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
