# Generated by Django 5.0.3 on 2024-09-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_sales_product_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_stock',
            new_name='in_stock',
        ),
    ]
