# Generated by Django 5.0.3 on 2024-09-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='empty_star',
            field=models.PositiveIntegerField(default=5, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
