# Generated by Django 5.0.3 on 2024-09-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_product_empty_star_product_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='empty_star',
        ),
        migrations.RemoveField(
            model_name='product',
            name='star',
        ),
    ]
