# Generated by Django 5.0.3 on 2024-09-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='percent_discount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
