# Generated by Django 5.0.3 on 2025-02-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_product_battery_capacity_product_processor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
