# Generated by Django 5.0.3 on 2024-03-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='عنوان تصویر')),
                ('image', models.ImageField(upload_to='ad/images', verbose_name='تصویر')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدی هدر',
                'verbose_name_plural': 'تصاویر اسلایدی هدر',
            },
        ),
    ]
