# Generated by Django 5.0.3 on 2024-03-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='عنوان تصویر')),
                ('image', models.ImageField(upload_to='ad/images', verbose_name='تصویر')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'تصویر بنر میانه سایت',
                'verbose_name_plural': 'تصاویر بنر های میانه سایت',
            },
        ),
    ]
