# Generated by Django 5.0.3 on 2025-01-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_alter_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='ad/images', verbose_name='تصویر'),
        ),
    ]
