# Generated by Django 5.0.3 on 2025-01-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_alter_carousel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='link',
            field=models.CharField(default=1, max_length=500, verbose_name='لینک'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='midbanners',
            name='link',
            field=models.CharField(default=1, max_length=500, verbose_name='لینک'),
            preserve_default=False,
        ),
    ]
