choices = [
    ('tehran', 'تهران'),
    ('alborz', 'البرز'),
    ('isfahan', 'اصفهان'),
    ('fars', 'فارس'),
    ('khorasan_razavi', 'خراسان رضوی'),
    ('khuzestan', 'خوزستان'),
    ('mazandaran', 'مازندران'),
    ('east_azarbaijan', 'آذربایجان شرقی'),
    ('west_azarbaijan', 'آذربایجان غربی'),
    ('gilan', 'گیلان'),
    ('hamadan', 'همدان'),
    ('kermanshah', 'کرمانشاه'),
    ('markazi', 'مرکزی'),
    ('qom', 'قم'),
    ('semnan', 'سمنان'),
    ('sistan_baluchestan', 'سیستان و بلوچستان'),
    ('yazd', 'یزد'),
    ('ardebil', 'اردبیل'),
    ('chaharmahal_bakhtiari', 'چهارمحال و بختیاری'),
    ('golestan', 'گلستان'),
    ('hamedan', 'همدان'),
    ('hormozgan', 'هرمزگان'),
    ('ilam', 'ایلام'),
    ('kerman', 'کرمان'),
    ('kurdistan', 'کردستان'),
    ('lorestan', 'لرستان'),
    ('qazvin', 'قزوین'),
    ('kohgiluyeh_boyer_ahmad', 'کهگیلویه و بویراحمد'),
    ('north_khorasan', 'خراسان شمالی'),
    ('south_khorasan', 'خراسان جنوبی'),
    ('bushehr', 'بوشهر'),
    ('zanjan', 'زنجان')
]