# Generated by Django 5.0.3 on 2024-07-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='faq_id',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
