# Generated by Django 5.0.3 on 2024-07-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_faq_faq_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='faq_id',
        ),
        migrations.AddField(
            model_name='faq',
            name='num',
            field=models.CharField(default='One', max_length=10),
        ),
    ]
