# Generated by Django 5.0.3 on 2024-08-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_about_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='image',
            field=models.ImageField(default=1, upload_to='index/images'),
            preserve_default=False,
        ),
    ]
