# Generated by Django 5.0.3 on 2024-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_personnel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, max_length=400, null=True)),
                ('facebook', models.CharField(blank=True, max_length=400, null=True)),
                ('x', models.CharField(blank=True, max_length=400, null=True)),
                ('youtube', models.CharField(blank=True, max_length=400, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
