# Generated by Django 5.0.3 on 2025-01-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='enamad',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='etehadie',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='samandehi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
