# Generated by Django 5.0.3 on 2025-02-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
